Repository BlyznytsiaOrg/bring, pull requests merged in 2023-12, with the labels that each got.

#103 [BLZT-102] add annotation and exceptions to Code.md file
  features/Core.md
Labels: size/M

#96 Feature/blzt 70
  core/src/main/java/com/bobocode/bring/core/BringApplication.java
  core/src/main/java/com/bobocode/bring/core/utils/Banner.java
  core/src/test/java/com/bobocode/bring/core/banner/BannerTest.java
  core/src/test/resources/banner.txt
  features/Core.md
  features/core/Banner.md
  features/web/servlet/RestApi.md
  web/src/main/java/com/bobocode/bring/web/BringWebApplication.java
  web/src/main/java/com/bobocode/bring/web/servlet/FrameworkServlet.java
Labels: size/L

#104 [BLZT-72] - @PreDestroy was added
  core/src/main/java/com/bobocode/bring/core/annotation/PreDestroy.java
  core/src/main/java/com/bobocode/bring/core/context/BringBeanFactory.java
  core/src/main/java/com/bobocode/bring/core/context/impl/DefaultBringBeanFactory.java
  core/src/main/java/com/bobocode/bring/core/exception/PreDestroyException.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/core/predestroy/PredestroyTest.java
  core/src/test/java/testdata/predestroy/negative/Messenger.java
  core/src/test/java/testdata/predestroy/positive/Messenger.java
  web/src/main/java/com/bobocode/bring/web/server/ServletWebServerFactory.java
  web/src/main/java/com/bobocode/bring/web/server/TomcatServletWebServerFactory.java
  web/src/main/java/com/bobocode/bring/web/servlet/BringTomcatApplicationLifecycleListener.java
  web/src/main/java/com/bobocode/bring/web/servlet/WebStarter.java
  web/src/test/java/com/bobocode/bring/web/PredestroyTest.java
  web/src/test/java/testdata/predestroy/Messenger.java
Labels: size/L

#107 BLZT-21 add doc
  features/Core.md
  features/core/Collections.md
Labels: size/L

#108 [BLZT-47] Added md files for Configuration
  features/Core.md
  features/core/Autowired.md
  features/core/Component.md
  features/core/Configuration.md
  features/core/Prototype.md
  features/core/Singleton.md
Labels: size/L

#112 [BLZT-70] PreDestroy in Core.md
  features/Core.md
Labels: size/XS

#115 BLZT add ukrainian logo
  core/src/main/java/com/bobocode/bring/core/utils/Banner.java
Labels: size/XS

#114 rename organization change old link to new one.
  README.md
  features/Core.md
  features/Overview.md
  features/Web.md
  features/core/Banner.md
  features/core/Logging.md
  pom.xml
Labels: size/M

#118 Maven central repo
  README.md
  features/Core.md
  features/Web.md
Labels: size/XS

#117 Update README.md
  README.md
Labels: size/XS

#119 Update Banner.md
  features/core/Banner.md
Labels: size/XS

#121 badges maven
  features/Core.md
  features/Overview.md
  features/Web.md
Labels: size/XS

#120 Update README.md
  README.md
Labels: size/XS

#122 Update README.md
  README.md
Labels: size/XS
