Repository BlyznytsiaOrg/bring, pull requests merged in 2023-11, with the labels that each got.

#2 feature/BLZT-1: add missing dependency for jakarta.servlet.jsp-api & …
  web/pom.xml
  web/src/main/java/com/bobocode/bring/web/BringStarterApplication.java
  web/src/main/java/com/bobocode/bring/web/WebStarter.java
  web/src/main/java/com/bobocode/bring/web/configuration/WebServerConfiguration.java
  web/src/main/java/com/bobocode/bring/web/embeddedTomcat/TomcatServletWebServerFactory.java
  web/src/main/java/com/bobocode/bring/web/http/HttpHeaders.java
  web/src/main/java/com/bobocode/bring/web/servlet/BaseServlet.java
  web/src/main/java/com/bobocode/bring/web/servlet/DispatcherServlet.java
  web/src/main/java/com/bobocode/bring/web/servlet/ServletWebServerFactory.java
Labels: size/L

#8 BLZT-7: add DI draft arch and some java doc for main components.
  README.md
  core/src/main/java/com/bobocode/bring/core/BringApplication.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScannerFactory.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/BeanPostProcessorDefinitionFactory.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/BeanPostProcessorFactory.java
Labels: size/L

#14 BLZT-13: add dependency for slf4j-api & logback-core & logback-classic.
  core/pom.xml
  core/src/main/java/com/bobocode/bring/core/BringApplication.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScannerFactory.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/BeanPostProcessorDefinitionFactory.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/BeanPostProcessorFactory.java
  core/src/main/resources/logback.xml
  core/src/test/resources/logback-test.xml
Labels: size/M

#16 Blzt 15: add test to validate Cyclic dependency & fix test with interface injection.
  core/src/main/java/com/bobocode/bring/core/BringApplication.java
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextNegativeCasesTest.java
  core/src/test/java/com/bobocode/bring/testdata/di/negative/contract/Barista.java
  core/src/test/java/com/bobocode/bring/testdata/di/negative/cyclic/A.java
  core/src/test/java/com/bobocode/bring/testdata/di/negative/cyclic/B.java
Labels: size/M

#18 [BLZT-9] Fixed autowired constructor DI bug
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanDefinition.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/impl/ConfigurationClassPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextNegativeCasesTest.java
  core/src/test/java/com/bobocode/bring/testdata/di/negative/contract/Drink.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/configuration/client/RestClient.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/configuration/configuration/TestConfiguration.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/configuration/service/BringService.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/constructor/BringBeansService.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/constructor/BringComponent.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/constructor/BringService.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/contract2/Barista.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/contract2/Drink.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/contract2/Espresso.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/contract2/Latte.java
  core/src/test/java/test/ComponentBeansCreationTest.java
  core/src/test/java/test/ConfigurationBeansCreationTest.java
Labels: size/L

#19 [BLZT-9] Added unit tests
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextNegativeCasesTest.java
  core/src/test/java/com/bobocode/bring/testdata/di/negative/configuration/A.java
  core/src/test/java/com/bobocode/bring/testdata/di/negative/configuration/AppConfiguration.java
  core/src/test/java/com/bobocode/bring/testdata/di/negative/configuration/B.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/fullinjection/AppConfiguration.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/fullinjection/ExternalService.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/fullinjection/ExternalService1.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/fullinjection/ExternalService2.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/fullinjection/GetInfoFromExternalServicesUseCase.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/fullinjection/RestClient.java
Labels: size/L

#24 BLZT-20: add support Properties injection (via @Value) and profile su…
  core/src/main/java/com/bobocode/bring/core/anotation/Profile.java
  core/src/main/java/com/bobocode/bring/core/anotation/Value.java
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/impl/DefaultBringBeanFactory.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScannerFactory.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ProfileClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/type/FieldValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/ParameterValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/PropertyFieldValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/PropertyParameterValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/TypeResolverFactory.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanDefinition.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanTypeEnum.java
  core/src/main/java/com/bobocode/bring/core/env/BringSourceLoader.java
  core/src/main/java/com/bobocode/bring/core/env/BringSourceScanner.java
  core/src/main/java/com/bobocode/bring/core/env/impl/BringPropertiesSourceScanner.java
  core/src/main/java/com/bobocode/bring/core/env/impl/BringPropertySourceLoader.java
  core/src/main/java/com/bobocode/bring/core/env/impl/ProfileSourceResolve.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/BeanPostProcessorDefinitionFactory.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/impl/ValuePropertiesPostProcessor.java
  core/src/main/resources/META-INF/bring-configuration-metadata.json
  core/src/main/resources/application.properties
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/core/env/impl/BringPropertiesSourceScannerTest.java
  core/src/test/java/com/bobocode/bring/core/env/impl/BringPropertySourceLoaderTest.java
  core/src/test/java/com/bobocode/bring/core/env/impl/ProfileSourceResolveTest.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/constructorproperties/ProfileBeanConstructor.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/fieldproperties/ProfileBean.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/setterproperties/ProfileBeanSetter.java
  core/src/test/resources/application-test.properties
  core/src/test/resources/application-uat.properties
  core/src/test/resources/application.properties
Labels: size/XL

#26 [BLZT-12] add ExceptionHandler implementation
  web/pom.xml
  web/src/main/java/com/bobocode/bring/web/WebStarter.java
  web/src/main/java/com/bobocode/bring/web/annotation/ResponseStatus.java
  web/src/main/java/com/bobocode/bring/web/configuration/WebServerConfiguration.java
  web/src/main/java/com/bobocode/bring/web/dto/ErrorResponse.java
  web/src/main/java/com/bobocode/bring/web/http/HttpStatus.java
  web/src/main/java/com/bobocode/bring/web/http/MediaType.java
  web/src/main/java/com/bobocode/bring/web/service/ErrorResponseCreator.java
  web/src/main/java/com/bobocode/bring/web/servlet/JsonExceptionHandler.java
  web/src/test/java/RestControllerTest.java
  web/src/test/java/testdata/controller/ExampleServlet.java
  web/src/test/java/testdata/exception/TestCustomException.java
Labels: size/XL

#25 BLZT-21 autowire list
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/type/FieldListValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/FieldValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/ParameterListValueTypeInjectorImpl.java
  core/src/main/java/com/bobocode/bring/core/context/type/PropertyFieldValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/TypeResolverFactory.java
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/listconstructorinjector/AConstructor.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/listconstructorinjector/B.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/listconstructorinjector/C.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/listconstructorinjector/IA.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/listfieldinjector/AField.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/listfieldinjector/B.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/listfieldinjector/C.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/listfieldinjector/IA.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/listsetterinjector/ASetter.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/listsetterinjector/B.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/listsetterinjector/C.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/listsetterinjector/IA.java
Labels: size/L

#29 [BLZT-22] Prototype Bean Scope
  core/src/main/java/com/bobocode/bring/core/anotation/Scope.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ConfigurationBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/impl/DefaultBringBeanFactory.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanDefinition.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanTypeEnum.java
  core/src/main/java/com/bobocode/bring/core/exception/BringGeneralException.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/impl/ConfigurationClassPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/utils/BeanScopeUtils.java
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/Barista.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/SimpleClass.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/TestConfiguration.java
Labels: size/L

#33 BLZT-32: fix NoSuchBeanException to NoUniqueBeanException when we hav…
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/exception/NoUniqueBeanException.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextNegativeCasesTest.java
  core/src/test/java/com/bobocode/bring/testdata/di/negative/oneinterfacetwodependency/Barista.java
  core/src/test/java/com/bobocode/bring/testdata/di/negative/oneinterfacetwodependency/Drink.java
  core/src/test/java/com/bobocode/bring/testdata/di/negative/oneinterfacetwodependency/Espresso.java
  core/src/test/java/com/bobocode/bring/testdata/di/negative/oneinterfacetwodependency/Latte.java
Labels: size/M

#35 [BLZT-22] Scoped Proxy
  core/src/main/java/com/bobocode/bring/core/anotation/Scope.java
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanDefinition.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanScope.java
  core/src/main/java/com/bobocode/bring/core/domain/ProxyMode.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/impl/ConfigurationClassPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/utils/BeanScopeUtils.java
  core/src/main/java/com/bobocode/bring/core/utils/ProxyUtils.java
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/off/Barista.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/off/CoffeeShop.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/off/SimpleClass.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/off/TestConfiguration.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/on/Barista.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/on/CoffeeShop.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/on/SimpleClass.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/on/TestConfiguration.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/onwithinterface/Barista.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/onwithinterface/CoffeeShop.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/onwithinterface/IBarista.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/onwithinterface/SimpleClass.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/prototype/onwithinterface/TestConfiguration.java
Labels: size/L

#40 BLZT-39: Update logback xml add core and web packages for override
  core/src/main/java/com/bobocode/bring/core/env/impl/BringPropertiesSourceScanner.java
  core/src/main/java/com/bobocode/bring/core/env/impl/BringPropertySourceLoader.java
  core/src/main/java/com/bobocode/bring/core/env/impl/ProfileSourceResolve.java
  core/src/main/java/com/bobocode/bring/core/utils/LogLevelChangerUtils.java
  core/src/main/resources/logback.xml
Labels: size/M

#45 BLZT-43: add java doc for core main component.
  core/src/main/java/com/bobocode/bring/core/anotation/Controller.java
  core/src/main/java/com/bobocode/bring/core/anotation/Profile.java
  core/src/main/java/com/bobocode/bring/core/anotation/RestController.java
  core/src/main/java/com/bobocode/bring/core/anotation/Value.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/AnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ComponentBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ControllerBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/InterfaceBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/RestControllerBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ServiceBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/bpp/BeanPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/bpp/BeanPostProcessorFactory.java
  core/src/main/java/com/bobocode/bring/core/bpp/impl/ScheduleBeanPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/bpp/impl/schedule/CustomScheduleConfiguration.java
  core/src/main/java/com/bobocode/bring/core/bpp/impl/schedule/CustomScheduler.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScannerFactory.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ComponentClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ControllerClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ProfileClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/RestControllerClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ServiceClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/env/BringSourceLoader.java
  core/src/main/java/com/bobocode/bring/core/env/BringSourceScanner.java
  core/src/main/java/com/bobocode/bring/core/env/impl/BringPropertiesSourceScanner.java
  core/src/main/java/com/bobocode/bring/core/env/impl/BringPropertySourceLoader.java
  core/src/main/java/com/bobocode/bring/core/env/impl/ProfileSourceResolve.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/BeanPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/impl/ValuePropertiesPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/utils/LogLevelChangerUtils.java
Labels: size/XL

#36 Draft readme with structure Overview, Core, Web
  Core.md
  Overview.md
  README.md
  Web.md
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/core/injection/package-info.java
  core/src/test/java/com/bobocode/bring/core/injection/value/BringValueInjectionTest.java
  core/src/test/java/com/bobocode/bring/testdata/di/negative/fieldproperties/NotFoundValue.java
  features/core/Scheduling.md
  features/core/Value.md
Labels: size/L

#48 [BLZT-47] Javadocs, refactoring
  core/src/main/java/com/bobocode/bring/core/anotation/Bean.java
  core/src/main/java/com/bobocode/bring/core/anotation/Configuration.java
  core/src/main/java/com/bobocode/bring/core/anotation/Scope.java
  core/src/main/java/com/bobocode/bring/core/context/BeanDefinitionRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/impl/DefaultBringBeanFactory.java
Labels: size/L

#54 [BLZT-23] - Primary & Qualifier
  core/src/main/java/com/bobocode/bring/core/anotation/Primary.java
  core/src/main/java/com/bobocode/bring/core/anotation/Qualifier.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ComponentBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/impl/DefaultBringBeanFactory.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanDefinition.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/impl/ConfigurationClassPostProcessor.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/primary/bean/Config.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/primary/bean/Employee.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/primary/component/A.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/primary/component/B.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/primary/component/C.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/primary/component/I.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/qualifier/constructor/ClassicMusic.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/qualifier/constructor/Music.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/qualifier/constructor/MusicPlayer.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/qualifier/constructor/RockMusic.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/qualifier/field/CanonPrinter.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/qualifier/field/LexmarkPrinter.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/qualifier/field/PrintService.java
  core/src/test/java/com/bobocode/bring/testdata/di/positive/qualifier/field/Printer.java
Labels: size/L

#52 [BLZT-10,11] added RestControllerContext class and store RestControll…
  web/src/main/java/com/bobocode/bring/web/servlet/BaseServlet.java
  web/src/main/java/com/bobocode/bring/web/servlet/DispatcherServlet.java
  web/src/main/java/com/bobocode/bring/web/servlet/RestControllerContext.java
  web/src/main/java/com/bobocode/bring/web/servlet/WebStarter.java
  web/src/main/java/com/bobocode/bring/web/servlet/data/ExampleRestController.java
  web/src/main/java/com/bobocode/bring/web/servlet/exception/RequestPathDuplicateException.java
  web/src/main/java/com/bobocode/bring/web/servlet/mapping/RestControllerParams.java
  web/src/main/java/com/bobocode/bring/web/servlet/mapping/request/DeleteParamsResolver.java
  web/src/main/java/com/bobocode/bring/web/servlet/mapping/request/GetParamsResolver.java
  web/src/main/java/com/bobocode/bring/web/servlet/mapping/request/PostParamsResolver.java
  web/src/main/java/com/bobocode/bring/web/servlet/mapping/request/PutParamsResolver.java
  web/src/main/java/com/bobocode/bring/web/servlet/mapping/request/RequestParamsResolver.java
  web/src/main/java/com/bobocode/bring/web/servlet/mapping/response/ResponseAnnotationResolver.java
  web/src/main/java/com/bobocode/bring/web/servlet/mapping/response/ResponseStatusAnnotationResolver.java
  web/src/main/java/com/bobocode/bring/web/utils/HttpServletRequestUtils.java
  web/src/main/java/com/bobocode/bring/web/utils/RestControllerParamsUtil.java
  web/src/test/java/testdata/controller/ExampleRestController.java
Labels: size/L

#56 BLZT-43: small refactoring for AnnotationBringBeanRegistry.
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScannerFactory.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ComponentClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ConfigurationClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ControllerClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ProfileClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/RestControllerClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ServiceClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
Labels: size/L

#58 Feature/blzt 43 annotation bring bean registrator
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BeanCreator.java
  core/src/main/java/com/bobocode/bring/core/context/impl/ConfigurationBeanRegistrar.java
  core/src/main/java/com/bobocode/bring/core/context/impl/ConstructorBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/impl/FieldBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/impl/SetterBeanInjection.java
Labels: size/XL

#60 BLZT-43: refactor TypeResolverFactory remove not needed instance for …
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BeanCreator.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/impl/ConstructorBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/impl/DefaultBringBeanFactory.java
  core/src/main/java/com/bobocode/bring/core/context/impl/FieldBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/impl/SetterBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/type/AbstractValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/FieldListValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/ParameterListValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/TypeResolverFactory.java
Labels: size/L

#62 Feature/blzt 10 11 rest controller bean post processor
  Overview.md
  README.md
  core/src/main/java/com/bobocode/bring/core/anotation/BeanProcessor.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ComponentBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ConfigurationBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ControllerBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/InterfaceBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ServiceBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/bpp/BeanPostProcessorFactory.java
  core/src/main/java/com/bobocode/bring/core/bpp/impl/ScheduleBeanPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScannerFactory.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ComponentClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ConfigurationClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ProfileClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ServiceClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/exception/BeanPostProcessorConstructionLimitationException.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/BeanPostProcessorDefinitionFactory.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/impl/ConfigurationClassPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/impl/ValuePropertiesPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
  web/src/main/java/com/bobocode/bring/web/servlet/bbp/RestControllerBeanPostProcessor.java
  web/src/main/java/com/bobocode/bring/web/servlet/exception/MissingBringServletImplException.java
  web/src/main/java/com/bobocode/bring/web/servlet/scaner/ControllerClassPathScanner.java
  web/src/main/java/com/bobocode/bring/web/servlet/scaner/RestControllerClassPathScanner.java
  web/src/main/java/com/bobocode/bring/web/servlet/scaner/resolver/RestControllerBeanNameAnnotationResolver.java
Labels: size/L

#61 BLZT-43: add the possibility to register external Beam Processor like…
  Overview.md
  README.md
  core/src/main/java/com/bobocode/bring/core/anotation/BeanProcessor.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ComponentBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ConfigurationBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ControllerBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/InterfaceBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/anotation/resolver/impl/ServiceBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/bpp/impl/ScheduleBeanPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScannerFactory.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ComponentClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ConfigurationClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ProfileClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ServiceClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/BeanPostProcessorDefinitionFactory.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/impl/ConfigurationClassPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/impl/ValuePropertiesPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
  web/src/main/java/com/bobocode/bring/web/servlet/scaner/ControllerClassPathScanner.java
  web/src/main/java/com/bobocode/bring/web/servlet/scaner/RestControllerClassPathScanner.java
  web/src/main/java/com/bobocode/bring/web/servlet/scaner/resolver/RestControllerBeanNameAnnotationResolver.java
Labels: size/L

#63 [BLZT-10,11] fix system path error
  web/src/main/java/com/bobocode/bring/web/service/impl/StaticResourceServiceImpl.java
  web/src/test/java/com/bobocode/bring/web/StaticResourceControllerIntegrationTest.java
Labels: size/M

#64 [BLZT-23] Moved Controller annotations to web module
  core/src/main/java/com/bobocode/bring/core/anotation/Bean.java
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/ConfigurationBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/ConstructorBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/impl/DefaultBringBeanFactory.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanDefinition.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanTypeEnum.java
  core/src/main/java/com/bobocode/bring/core/postprocessor/impl/ConfigurationClassPostProcessor.java
  core/src/test/java/testdata/di/positive/configuration/configuration/TestConfiguration.java
  core/src/test/java/testdata/di/positive/fullinjection/AppConfiguration.java
  core/src/test/java/testdata/di/positive/fullinjection/ExternalService1.java
  web/src/main/java/com/bobocode/bring/web/servlet/StaticResourceController.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/Controller.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/RestController.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/resolver/ControllerBeanNameAnnotationResolver.java
  web/src/main/java/com/bobocode/bring/web/servlet/bbp/RestControllerBeanPostProcessor.java
  web/src/main/java/com/bobocode/bring/web/servlet/scaner/ControllerClassPathScanner.java
  web/src/main/java/com/bobocode/bring/web/servlet/scaner/RestControllerClassPathScanner.java
  web/src/main/java/com/bobocode/bring/web/servlet/scaner/resolver/RestControllerBeanNameAnnotationResolver.java
  web/src/test/java/testdata/controller/ExampleRestController.java
Labels: size/M

#67 BLZT-43: add java doc & tests for dependency injection via field, setter and constructor
  core/src/main/java/com/bobocode/bring/core/context/BringBeanFactory.java
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BeanCreator.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/impl/ConfigurationBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/ConstructorBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/impl/DefaultBringBeanFactory.java
  core/src/main/java/com/bobocode/bring/core/context/impl/FieldBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/impl/SetterBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScannerFactory.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ComponentClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ServiceClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/exception/BeansException.java
  core/src/main/java/com/bobocode/bring/core/exception/NoSuchBeanException.java
  core/src/main/java/com/bobocode/bring/core/exception/NotFoundBeanException.java
  core/src/test/java/com/bobocode/bring/core/bpp/impl/ScheduleBeanPostProcessorTest.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/core/injection/constructor/BringConstructorInjectionTest.java
  core/src/test/java/com/bobocode/bring/core/injection/field/BringFieldInjectionTest.java
  core/src/test/java/com/bobocode/bring/core/injection/setter/BringSetterInjectionTest.java
  core/src/test/java/testdata/di/negative/field/A.java
  core/src/test/java/testdata/di/negative/field/B.java
  core/src/test/java/testdata/di/negative/noclassimplementation/Barista.java
  core/src/test/java/testdata/di/negative/noclassimplementation/Latte.java
  core/src/test/java/testdata/di/negative/nofieldinterfaceimplementation/A.java
  core/src/test/java/testdata/di/negative/nofieldinterfaceimplementation/B.java
  core/src/test/java/testdata/di/negative/noimplementation/Barista.java
  core/src/test/java/testdata/di/negative/noimplementation/Drink.java
  core/src/test/java/testdata/di/negative/noimplementationviasetter/A.java
  core/src/test/java/testdata/di/negative/noimplementationviasetter/B.java
  core/src/test/java/testdata/di/negative/secondconstructor/A.java
  core/src/test/java/testdata/di/negative/secondconstructor/B.java
  core/src/test/java/testdata/di/negative/setter/A.java
  core/src/test/java/testdata/di/negative/setter/B.java
  core/src/test/java/testdata/scheduler/MyCustomScheduler.java
Labels: size/XL

#69 [BLZT-47] Added unit tests
  core/src/main/java/com/bobocode/bring/core/bfpp/BeanFactoryPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/bfpp/BeanPostProcessorDefinitionFactory.java
  core/src/main/java/com/bobocode/bring/core/bfpp/impl/ConfigurationClassPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/bfpp/impl/ValuePropertiesPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/exception/NoUniqueBeanException.java
  core/src/main/java/com/bobocode/bring/core/utils/ProxyUtils.java
  core/src/main/java/com/bobocode/bring/core/utils/TypeCast.java
  core/src/main/resources/logback.xml
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextNegativeCasesTest.java
  core/src/test/java/com/bobocode/bring/core/env/impl/BringPropertiesSourceScannerTest.java
  core/src/test/java/testdata/di/negative/configuration/noconfigbean/AppConfiguration.java
  core/src/test/java/testdata/di/negative/configuration/nosuchbean/AppConfiguration.java
  core/src/test/java/testdata/di/negative/configuration/notabean/AppConfiguration.java
  core/src/test/java/testdata/di/negative/configuration/nouniquebean/AppConfiguration.java
  core/src/test/java/testdata/di/positive/configuration/client/RestClient.java
  core/src/test/java/testdata/di/positive/configuration/configuration/TestConfiguration.java
Labels: size/L

#81 [BLZT-47] Fixed Qualifier for configuration
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
  core/src/test/java/testdata/di/positive/configuration/configuration/TestConfiguration.java
Labels: size/M

#82 BLZT-43: move MD to feature and add missing javadoc.
  README.md
  core/src/main/java/com/bobocode/bring/core/annotation/BeanProcessor.java
  core/src/main/java/com/bobocode/bring/core/annotation/resolver/impl/ConfigurationBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/context/BeanDefinitionRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/BeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/DefaultBringBeanFactory.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/impl/ConfigurationClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/exception/BeanAnnotationMissingException.java
  core/src/main/java/com/bobocode/bring/core/exception/BeanPostProcessorConstructionLimitationException.java
  core/src/main/java/com/bobocode/bring/core/exception/BringGeneralException.java
  core/src/main/java/com/bobocode/bring/core/exception/CyclicBeanException.java
  core/src/main/java/com/bobocode/bring/core/exception/NoConstructorWithAutowiredAnnotationBeanException.java
  core/src/main/java/com/bobocode/bring/core/exception/NoSuchBeanException.java
  core/src/main/java/com/bobocode/bring/core/exception/NoUniqueBeanException.java
  core/src/main/java/com/bobocode/bring/core/exception/PropertyValueNotFoundException.java
  core/src/test/java/com/bobocode/bring/core/domain/BeanTypeEnumTest.java
  features/Core.md
  features/Overview.md
  features/Web.md
  web/pom.xml
  web/src/main/java/com/bobocode/bring/web/BringWebApplication.java
  web/src/main/java/com/bobocode/bring/web/TomcatApplication.java
  web/src/main/java/com/bobocode/bring/web/servlet/data/ExampleRestController.java
Labels: size/L

#85 [BLZT-47] Fixed inject non-config bean into config bean
  core/src/main/java/com/bobocode/bring/core/annotation/resolver/AnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/annotation/resolver/impl/ComponentBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/annotation/resolver/impl/ConfigurationBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/annotation/resolver/impl/InterfaceBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/annotation/resolver/impl/ServiceBeanNameAnnotationResolver.java
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BeanCreator.java
  core/src/main/java/com/bobocode/bring/core/context/impl/ConfigurationBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/ConstructorBeanInjection.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextNegativeCasesTest.java
  core/src/test/java/com/bobocode/bring/core/injection/cyclic/BringApplicationContextCyclicDependencyTest.java
  core/src/test/java/testdata/di/positive/configuration/configuration/TestConfiguration.java
  core/src/test/java/testdata/di/positive/fullinjection/AppConfiguration.java
  core/src/test/java/testdata/di/positive/fullinjection/DefaultRestClient.java
  web/src/main/java/com/bobocode/bring/web/servlet/JsonExceptionHandler.java
Labels: size/L

#74 BLZT-49 adding some logs
  Core.md
  core/src/main/java/com/bobocode/bring/core/BringApplication.java
  core/src/main/java/com/bobocode/bring/core/bpp/impl/ScheduleBeanPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BeanCreator.java
  core/src/main/java/com/bobocode/bring/core/context/impl/BringApplicationContext.java
  core/src/main/java/com/bobocode/bring/core/context/impl/DefaultBringBeanFactory.java
  core/src/main/java/com/bobocode/bring/core/context/impl/FieldBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScannerFactory.java
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
  core/src/main/resources/logback.xml
  core/src/test/resources/logback-test.xml
  features/core/Logging.md
  web/src/main/java/com/bobocode/bring/web/BringWebApplication.java
  web/src/main/java/com/bobocode/bring/web/servlet/DispatcherServlet.java
  web/src/main/java/com/bobocode/bring/web/servlet/RestControllerContext.java
  web/src/main/java/com/bobocode/bring/web/servlet/WebStarter.java
  web/src/main/java/com/bobocode/bring/web/servlet/mapping/request/DeleteParamsResolver.java
  web/src/main/java/com/bobocode/bring/web/servlet/mapping/request/GetParamsResolver.java
  web/src/main/java/com/bobocode/bring/web/servlet/mapping/request/PostParamsResolver.java
  web/src/main/java/com/bobocode/bring/web/servlet/mapping/request/PutParamsResolver.java
  web/src/test/resources/logback-test.xml
Labels: size/L

#79 Feature/blzt 10 11 markdown
  Web.md
  features/web/server/TomcatWebServer.md
  features/web/server/exception/ConnectorStartFailedException.md
  features/web/server/exception/WebServerException.md
  features/web/servlet/DispatcherServlet.md
  features/web/servlet/StaticResourceController.md
  features/web/servlet/annotation/Controller.md
  features/web/servlet/annotation/DeleteMapping.md
  features/web/servlet/annotation/GetMapping.md
  features/web/servlet/annotation/PatchMapping.md
  features/web/servlet/annotation/PathVariable.md
  features/web/servlet/annotation/PostMapping.md
  features/web/servlet/annotation/PutMapping.md
  features/web/servlet/annotation/RequestBody.md
  features/web/servlet/annotation/RequestHeader.md
  features/web/servlet/annotation/RequestMapping.md
  features/web/servlet/annotation/RequestParam.md
  features/web/servlet/annotation/RestController.md
  features/web/servlet/exception/MethodArgumentTypeMismatchException.md
  features/web/servlet/exception/MissingApplicationMappingException.md
  features/web/servlet/exception/MissingBringServletImplException.md
  features/web/servlet/exception/MissingRequestHeaderAnnotationValueException.md
  features/web/servlet/exception/MissingRequestParamException.md
  features/web/servlet/exception/RequestBodyTypeUnsupportedException.md
  features/web/servlet/exception/RequestPathDuplicateException.md
  features/web/servlet/exception/TypeArgumentUnsupportedException.md
  web/src/main/java/com/bobocode/bring/web/servlet/DispatcherServlet.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/DeleteMapping.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/GetMapping.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/PatchMapping.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/PathVariable.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/PostMapping.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/PutMapping.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/RequestBody.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/RequestHeader.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/RequestMapping.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/RequestParam.java
  web/src/main/java/com/bobocode/bring/web/servlet/annotation/RestController.java
  web/src/main/java/com/bobocode/bring/web/staticcontent/controller/StaticResourceController.java
  web/src/test/java/com/bobocode/bring/web/BringContextCreationTest.java
  web/src/test/java/com/bobocode/bring/web/PathVariableTest.java
  web/src/test/java/com/bobocode/bring/web/RequestHeaderTest.java
  web/src/test/java/testdata/pathvariable/PathVariableController.java
  web/src/test/java/testdata/requestheader/RequestHeaderController.java
Labels: size/XL

#88 BLZT-43: small update JavaDoc and MD.
  Core.md
  Web.md
  core/src/main/java/com/bobocode/bring/core/annotation/Primary.java
  core/src/main/java/com/bobocode/bring/core/annotation/Qualifier.java
  core/src/main/java/com/bobocode/bring/core/context/impl/ConstructorBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/type/AbstractPropertyValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/ParameterListValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/PropertyFieldValueTypeInjector.java
  web/src/test/java/com/bobocode/bring/web/BringContextCreationTest.java
  web/src/test/java/com/bobocode/bring/web/JsonExceptionHandlerIntegrationTest.java
  web/src/test/java/com/bobocode/bring/web/MixConfigurationBeanAndRestControllerTest.java
  web/src/test/java/com/bobocode/bring/web/PathVariableTest.java
  web/src/test/java/com/bobocode/bring/web/RequestBodyTest.java
  web/src/test/java/com/bobocode/bring/web/RequestHeaderTest.java
  web/src/test/java/com/bobocode/bring/web/RequestParamTest.java
  web/src/test/java/com/bobocode/bring/web/RestControllerContextCreationTest.java
  web/src/test/java/com/bobocode/bring/web/RestControllerTest.java
  web/src/test/java/com/bobocode/bring/web/StaticResourceControllerIntegrationTest.java
Labels: size/M

#87 [BLZT-86] add set injection
  core/src/main/java/com/bobocode/bring/core/bpp/impl/ScheduleBeanPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/context/impl/FieldBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/impl/SetterBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScannerFactory.java
  core/src/main/java/com/bobocode/bring/core/context/type/AbstractValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/FieldListValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/ParameterListValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/TypeResolverFactory.java
  core/src/main/java/com/bobocode/bring/core/context/type/field/FieldListValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/field/FieldMapValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/field/FieldQueueValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/field/FieldSetValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/field/FieldValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/field/PropertyFieldValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/ParameterListValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/ParameterMapValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/ParameterQueueValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/ParameterSetValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/ParameterValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/PropertyParameterValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/core/injection/constructor/BringConstructorInjectionTest.java
  core/src/test/java/com/bobocode/bring/core/injection/field/BringFieldInjectionTest.java
  core/src/test/java/com/bobocode/bring/core/injection/setter/BringSetterInjectionTest.java
  core/src/test/java/testdata/di/positive/setconstructorinjector/AConstructor.java
  core/src/test/java/testdata/di/positive/setconstructorinjector/B.java
  core/src/test/java/testdata/di/positive/setconstructorinjector/C.java
  core/src/test/java/testdata/di/positive/setconstructorinjector/D.java
  core/src/test/java/testdata/di/positive/setconstructorinjector/IA.java
  core/src/test/java/testdata/di/positive/setfieldinjector/AField.java
  core/src/test/java/testdata/di/positive/setfieldinjector/B.java
  core/src/test/java/testdata/di/positive/setfieldinjector/C.java
  core/src/test/java/testdata/di/positive/setfieldinjector/D.java
  core/src/test/java/testdata/di/positive/setfieldinjector/IA.java
  core/src/test/java/testdata/di/positive/setsetterinjector/ASetter.java
  core/src/test/java/testdata/di/positive/setsetterinjector/B.java
  core/src/test/java/testdata/di/positive/setsetterinjector/C.java
  core/src/test/java/testdata/di/positive/setsetterinjector/IA.java
  web/src/main/java/com/bobocode/bring/web/servlet/DispatcherServlet.java
  web/src/main/java/com/bobocode/bring/web/servlet/exception/MissingApplicationMappingException.java
  web/src/main/java/com/bobocode/bring/web/staticcontent/exception/StaticFileNotFoundException.java
  web/src/main/java/com/bobocode/bring/web/staticcontent/service/impl/DefaultStaticResourceService.java
  web/src/test/java/com/bobocode/bring/web/StaticResourceControllerIntegrationTest.java
Labels: size/XXL

#90 BLZT-43: fix some tests.
  core/src/test/java/com/bobocode/bring/core/injection/constructor/BringConstructorInjectionTest.java
  core/src/test/java/com/bobocode/bring/core/injection/field/BringFieldInjectionTest.java
  core/src/test/java/com/bobocode/bring/core/injection/setter/BringSetterInjectionTest.java
  core/src/test/java/testdata/di/positive/setconstructorinjector/D.java
Labels: size/M

#91 BLZT-43: fix some tests.
  core/src/main/java/com/bobocode/bring/core/context/type/field/PropertyFieldValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/PropertyParameterValueTypeInjector.java
  pom.xml
  web/src/main/java/com/bobocode/bring/web/server/TomcatWebServer.java
  web/src/main/java/com/bobocode/bring/web/server/WebServer.java
  web/src/main/java/com/bobocode/bring/web/servlet/JsonExceptionHandler.java
Labels: size/S

#89 BLZT-71 add @PostConstruct functionality
  Core.md
  core/src/main/java/com/bobocode/bring/core/annotation/PostConstruct.java
  core/src/main/java/com/bobocode/bring/core/bpp/impl/PostConstructBeanPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/exception/PostConstructException.java
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
  core/src/test/java/com/bobocode/bring/core/bpp/impl/PostConstructBeanPostProcessorTest.java
  core/src/test/java/testdata/postconstruct/negative/CustomPostConstruct.java
  core/src/test/java/testdata/postconstruct/positive/CustomPostConstruct.java
  features/core/PostConstruct.md
Labels: size/L

#92 Feature/blzt 83
  Overview.md
  Web.md
  features/Core.md
  features/Overview.md
  features/Web.md
  features/core/Constructor.md
  features/core/Field.md
  features/core/PropertiesFileSupport.md
  features/core/Scheduling.md
  features/core/Setter.md
  features/core/Value.md
  features/web/servlet/ResponseEntity.md
  features/web/servlet/RestApi.md
  features/web/servlet/annotation/DeleteMapping.md
  features/web/servlet/annotation/GetMapping.md
  features/web/servlet/annotation/PatchMapping.md
  features/web/servlet/annotation/PathVariable.md
  features/web/servlet/annotation/PostMapping.md
  features/web/servlet/annotation/PutMapping.md
  features/web/servlet/annotation/RequestBody.md
  features/web/servlet/annotation/RequestHeader.md
  features/web/servlet/annotation/RequestMapping.md
  features/web/servlet/annotation/RequestParam.md
  features/web/servlet/annotation/ResponseStatus.md
  features/web/servlet/annotation/RestController.md
  features/web/servlet/exception/MissingBringServletImplException.md
  features/web/servlet/exception/MissingRequestHeaderAnnotationValueException.md
  features/web/servlet/exception/MissingRequestParamException.md
  features/web/servlet/exception/RequestBodyTypeUnsupportedException.md
  web/src/test/java/testdata/generalintegrationtest/ExampleRestController.java
Labels: size/L

#95 Feature/blzt 59
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
  core/src/main/java/com/bobocode/bring/core/context/impl/ConstructorBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/impl/FieldBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/impl/SetterBeanInjection.java
  core/src/main/java/com/bobocode/bring/core/context/type/AbstractValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/TypeResolverFactory.java
  core/src/main/java/com/bobocode/bring/core/context/type/field/FieldInterfaceValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/ParameterInterfaceValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/ParameterListValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/ParameterMapValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/ParameterQueueValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/ParameterSetValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/ParameterValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/context/type/parameter/PropertyParameterValueTypeInjector.java
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
  core/src/test/java/com/bobocode/bring/core/context/impl/BringApplicationContextHappyCasesTest.java
  core/src/test/java/com/bobocode/bring/core/injection/field/BringFieldInjectionTest.java
  core/src/test/java/com/bobocode/bring/core/injection/primary/PrimaryBeanInjectionTest.java
  core/src/test/java/com/bobocode/bring/core/injection/qualifier/QualifierBeanInjectionTest.java
  core/src/test/java/com/bobocode/bring/core/injection/setter/BringSetterInjectionTest.java
  core/src/test/java/com/bobocode/bring/core/injection/value/BringValueInjectionTest.java
  core/src/test/java/testdata/di/positive/qualifier/field/PrintService.java
Labels: size/L

#97 BLZT-43: add javadoc and some unittests.
  core/pom.xml
  core/src/main/java/com/bobocode/bring/core/bfpp/BeanFactoryPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/bpp/BeanPostProcessor.java
  core/src/main/java/com/bobocode/bring/core/context/scaner/ClassPathScanner.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanDefinition.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanScope.java
  core/src/main/java/com/bobocode/bring/core/domain/BeanTypeEnum.java
  core/src/main/java/com/bobocode/bring/core/domain/ProxyMode.java
  core/src/main/java/com/bobocode/bring/core/utils/BeanScopeUtils.java
  core/src/main/java/com/bobocode/bring/core/utils/Pair.java
  core/src/main/java/com/bobocode/bring/core/utils/ProxyUtils.java
  core/src/main/java/com/bobocode/bring/core/utils/ReflectionUtils.java
  core/src/main/java/com/bobocode/bring/core/utils/TypeCast.java
  core/src/test/java/com/bobocode/bring/core/utils/PairTest.java
  core/src/test/java/com/bobocode/bring/core/utils/ReflectionUtilsTest.java
  core/src/test/java/com/bobocode/bring/core/utils/TypeCastTest.java
Labels: size/XL

#98 [BLZT-47] AnnotationBringBeanRegistry Javadocs
  core/src/main/java/com/bobocode/bring/core/context/impl/AnnotationBringBeanRegistry.java
Labels: size/S
